baseurl: ""
url: https://71c1nw00n.github.io

markdown: kramdown
plugins:
  - jekyll-email-protect

collections:
  publications:
    output: false
  news:
    output: false
  showcase:
    output: true
  posts:
    output: true
